# Generated by Django 4.2.7 on 2025-03-26 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='题目内容')),
                ('wrong_answer', models.TextField(verbose_name='错误答案')),
                ('right_answer', models.TextField(verbose_name='正确答案')),
                ('subject', models.CharField(choices=[('chinese', '语文'), ('math', '数学'), ('english', '英语'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('history', '历史'), ('geography', '地理'), ('politics', '政治')], max_length=20, verbose_name='科目')),
                ('error_count', models.IntegerField(default=1, verbose_name='错误次数')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='mistakes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxValueValidator(2097152)], verbose_name='题目图片')),
            ],
            options={
                'verbose_name': '错题记录',
                'verbose_name_plural': '错题记录',
                'ordering': ['-add_date'],
            },
        ),
    ]
